### PR TITLE
added panels to recipes

### PR DESCRIPTION
**Pull request by RHTurnerNOLA**
Added Bootstrap panels to _form.html.erb and index.html.erb

### CODE REVIEW

**Comment by siakaramalegos** [comment]
Thanks for doing this - can you move the style element to one of the CSS pages?  Remember, a place for everything, everything in its place.  Put the style in the stylesheet.

**Comment by siakaramalegos** [comment]
Once you're done, push again and then re-do the pull request again (it may automatically update).

**Comment by RHTurnerNOLA** [comment]
Added Bootstrap panels to recipes, modified:  _form.html.erb, index.html.erb, and application.css

**Comment by siakaramalegos** [comment]
Thanks so much! :+1:

**Pull request merged**
